/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIForAdd */

#ifndef _Included_JNIForAdd
#define _Included_JNIForAdd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIForAdd
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNIForAdd_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
